account/urls.py
from django.urls import path
from .import views as v
urlpatterns = [
    path("",v.home,name="home"),
    path("about",v.about,name="about"),
    path("contact",v.contact,name="contact"),
    path("reg",v.register,name="register"),
    path("login",v.loginn,name="login"),
    path("logout",v.logoutt,name="logout")
]

ecommers1/urls.py
from django.contrib import admin
from django.urls import path,include
from account.views import home
from account import urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home),
    path("Acc-",include(("account.urls","account"),namespace="accountapp")),
    path("Pro-",include(("product.urls","product"),namespace="product"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .import views as v
app_name="cart"
urlpatterns = [
    path("product",v.product_list,name="product1"),
    path("showcart",v.show_Cart,name="showcart"),
    path("addtocart",v.Add_cart,name="addtocart"),
    path("del/<int:proid>",v.delete,name="delete"),
    path("pluscart/<int:pid>",v.plus_cart,name="pluscart"),
    path("minuscart/<int:pid>",v.minus_cart,name="minuscart"),
    path("search",v.search, name="srch"),
    path("order",v.order,name="order"),
    path("address",v.address,name="address")
    
   
]

account/models.py
from django.db import models

from django.db import models

from django import forms

class LoginForm(forms.Form):
   
    uname=forms.CharField(label="username",widget=forms.TextInput(attrs={'autofocus':'true', 'class':'form-control' }))
    pswd=forms.CharField(label="password",widget=forms.PasswordInput(attrs={'autofocus':'true', 'class':'form-control' }))

product/models.py
from django.db import models

# Create your models here.
from django.db import models

from django.contrib.auth.models import User
from django.shortcuts import reverse



class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='image/')

    def __str__(self):
        return self.name
    
class Cart(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    amount=models.IntegerField(default=0)
    total_amount=models.IntegerField(default=0)
    
    def total_cost(self):
        return self.quantity*self.product.price 
    

product/forms.py
from django import forms
from .models import *


class CartItem(forms.ModelForm):
    class Meta:
        model=Cart
        fields="__all__"

account/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth import login,logout,authenticate

from django.contrib.auth.models import User

def home(request):
    return render(request, "home.html")
def contact(request):
    return render (request,"contact.html")
def about(request):
    return render (request,"about.html")

 



def register(request):
    if request.method=="POST":
        obj=UserCreationForm(request.POST)
        obj.save()
        return redirect("/")
    else:
        d={"form":UserCreationForm}
        return render(request,'form.html ',d)
    

def loginn(request):
    if request.method=='POST':
        uname=request.POST.get("uname")
        pswd=request.POST.get("pswd")
        user=authenticate(request,username=uname,password=pswd)
        if user is not None:
            request.session["id"]=user.id
            print(request.session.get("id"))
            login(request,user)
            return redirect("/Pro-product")
        else:
            d={'form':LoginForm}
            return render(request,'login.html',d)

    else:
        d={'form':LoginForm}
        return render(request,'login.html',d)

def logoutt(request):
    logout(request)
    return redirect("/")    

product/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect, get_object_or_404

from .models import *
from .forms import *

def product_list(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'product_list.html', context)



def Add_cart(request):
    user_id=request.session.get("id")
    user=request.user
    product_id=request.GET.get("prod_id")
    

    product=Product.objects.get(id=product_id)
    
    Cart(user=user,product=product).save()
    return redirect("/Pro-product")


def show_Cart(request):
     ids=request.session.get("id")

     obj=Cart.objects.filter(user=ids)
     amount=0
     for p in obj:
            
            value= p.quantity * p.product.price
            amount= value + amount
     total_amount= amount +50
  
     d={'data':obj,'total_amount':total_amount,'amount':amount}
     
     return render(request,'cart.html',d)
    
def delete(request,proid):
    obj=Cart.objects.get(id=proid)
    obj.delete()
    return redirect("/Pro-showcart")






def plus_cart(request,pid):
    if request.method=="GET":
        obj1=Cart.objects.get(id=pid)
   
        obj1.quantity +=1
        obj1.save()
    
        user=request.user
        cart=Cart.objects.filter(user=user)
        amount=0

        for p in cart:
            
            value= p.quantity * p.product.price
            amount= value + amount
        total_amount= amount + 50
        data={
            "quantity":obj1.quantity,
            "amount":obj1.amount,
            "totalamount":obj1.total_amount,
            "price":value
        }
        return redirect("/Pro-showcart")

def minus_cart(request,pid):
    if request.method=="GET":
        c=Cart.objects.get(id=pid)
        c.quantity -=1
        c.save()
    
        user=request.user
        cart=Cart.objects.filter(user=user)
        if c.quantity==0:
            c.delete()
        amount=0    
        for p in cart:
            
            value= p.quantity *p.product.price
            amount= value + amount
        total_amount= amount + 50
        data={
            "quantity":c.quantity,
            "amount":c.amount,
            "totalamount":c.total_amount,
            "price":value
        }
        return redirect("/Pro-showcart")
    
def search(request):
  ids=request.session.get("id")

  srch=request.POST.get("srch")
  obj=Product.objects.filter(description__contains=srch)
  d={'products':obj}
  return render(request,'product_list.html',d) 

def order(request):
    ids=request.session.get("id")

    obj=Cart.objects.filter(user=ids)
    d={"data":obj}

    return render(request,"order.html",d)  


def address(request):
    
    return render (request,"address.html")

account/templates/form.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <title>Document</title>
<style>

.container  
{
    width: 390px;
    height: 400px;
    background: skyblue;
    color:black;
    font-size:100%;
    font-style:unset;
    top: 50%;
    left:50%;
    position:absolute;
    transform: translate(-50%,-50%);
    box-sizing: border-box;
    padding: 70px 30px;
}
.container p   
{
    
    margin: 0;
    padding: 0 0 20px;
    font-weight: bold;
    
}
.container input
{
    width: 100%;
    margin-bottom: 20px;
}    
.container input[type="text"], input[type="password"]
{
    border: none;
    border-bottom: 1px solid #fff;
    background:transparent;
    outline: none;
    height: 40  px;
    color: #fff;
    font-size: 16px;

}
.container input[type="submit"]
{
    border: none;
    outline: none;
    height: 40px;
    background: #fb2525;
    font-size: 18px;
    border-radius: 20px;


}
.container input[type="submit"]:hover
{
    cursor:pointer;
    background: #ffc107;
    color: #000;
}
.container a
{
    text-decoration:none;
    font-size: 12px;
    line-height: 20px;
    color:darkgray;
}
.container a
{
    color: #ffc107;
}


</style>    

</head>
<body>
    {% include "navbar.html"%}

<form action="" method="post">
    {%csrf_token%}
    <div class="container">
        <table border="1px">
            <tr>
            {% for obj in form %}
                {{obj.label_tag}}  {{obj}} {{obj.errors|striptags}} <br><br><br>

            {% endfor %}
           </tr>               
        </table>
        <input type="submit" value="submit" class="btn btn-dark">
        <div class="text-center text-primary fw-bold">
            <small>Existing User ? <a href="{%url 'account:login'%}" class="text-danger">Login</a>
            </small>
        </div>
    </div>      
</form>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


    
</body>
</html>

account/templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <title>Document</title>
    <style>
      

        .container {
            width: 390px;
            height: 500px;
            background: lightgrey;
            color: black;
            font-size: 100%;
            font-style: unset;
            top: 50%;
            left: 50%;
            position: absolute;
            transform: translate(-50%, -50%);
            box-sizing: border-box;
            padding: 70px 30px;
        }

        .container p {

            margin: 0;
            padding: 0 0 20px;
            font-weight: bold;

        }

        .container input {
            width: 100%;
            margin-bottom: 20px;
        }

        .container input[type="text"],
        input[type="password"] {
            border: none;
            border-bottom: 1px solid #fff;
            background: transparent;
            outline: none;
            height: 40 px;
            color: #fff;
            font-size: 16px;

        }

        .container input[type="submit"] {
            border: none;
            outline: none;
            height: 40px;
            background: #fb2525;
            font-size: 18px;
            border-radius: 20px;
            background-position: center;
            margin-right: 30px;


        }

        .container input[type="submit"]:hover {
            cursor: pointer;
            background: #ffc107;
            color: #000;
        }

        .container a {
            text-decoration: none;
            font-size: 12px;
            line-height: 20px;
            color: darkgray;
        }

        .container a {
            color: #ffc107;
        }
    </style>
</head>

<body>
    {% include "navbar.html"%}


    <form action="" method="post">
        {%csrf_token%}
        <div class="container">

            <table align="center">
                <tr>
                    <br>
                    <th>{{form.as_table}}</th>
                    <br>

                </tr>
            </table>
            <br>
            <input type="submit" value="submit" class="btn btn-dark" style="margin-trim: 80px;">

            <div class="text-center text-primary fw-bold">
                <small>Forgot Password<a href="#" class="text-danger">Change Password</a>
                </small>

                <small>Create Account <a href="{%url 'account:register'%}" class="text-danger">Register</a>
                </small>
            </div>


    </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

</body>

</html>

account/templates/navbar.html
<!doctype html>
<html lang="en">

<head>

    {%load static%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">



</head>

<body>
    {%if user.is_authenticated %}

    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{%url 'account:home'%}"><img src="{%static  'image/Group-133.svg'%}" style="height: 90px; width: 180px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li class="nav-item" style="margin-left: 25px;">
                        <a class="nav-link active" aria-current="page" href="{%url 'account:home'%}"
                            style="margin-right: 25px;"><img src="{%static  'image/home.png'%}"
                                style="width: 37px; height: 36px;"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'product:product1'%}"
                            style="color: aquamarine; font-size: 20px; margin-right: 25px;"><img
                                src="{%static  'image/layout.png'%}" style="width: 30px; height: 30px;"></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'product:showcart'%}" style="margin-right: 25px;"><img
                                src="{%static  'image/carts.png'%}" style="width: 35px; height: 30px;"></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <img src="{%static  'image/user.png'%}" style="width: 25px; height: 30px;">
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{%url 'account:logout'%}">logout</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search" action="{%url 'product:srch'%}" method="post">
                    {%csrf_token%}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srch">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {%else%}
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{%url 'account:home'%}">
                <img src="{%static  'image/Group-133.svg'%}" style="height: 90px; width: 180px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">MAFFEI FINE KITCHEN</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{%url 'account:contact'%}">Contact
                                us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'account:about'%}">About us</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false" style="font-weight: bold;">
                                User
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" href="{%url 'account:login'%}">Login</a></li>
                                <li><a class="dropdown-item" href="{%url 'account:register'%}">SinUp</a></li>
                            </ul>
                            <div id="registration-form-container"></div>
                </div>
            </div>
        </div>
    </nav>

    {%endif%}
   

</body>

product/templates/cart.html
<!DOCTYPE html>
<html>

<head>
    <title>My E-commerce Site</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<body style="background-color:
#e0e6eb;" >

    {% include "navbar.html" %}

{% block content %}
<div class="container my-5">
    <div class="row">
        {% if data %}
        <h1 class="text-center mb-5">Shopping Cart</h1>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body" style="background-color: aquamarine;">
                    <h3>Cart</h3>
                    {% for item in data %}
                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center"><img src="{{item.product.image.url}}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"></div>
                        <div class="col-sm-9">
                            <div><h5>{{item.product.title}}</h5>
                                <p class="mb-2 text-muted small">{{item.product.description}}</p>
                                <div class="my-3">
                                    <label for="quantity" >Quantity</label>
                                    <button><a href="{%url 'product:minuscart' item.id %}" name="pid" class="minus-cart btn" pid="{{item.product.id}}"><i class="fas fa-minus-square fa-lg"></i>-</a></button>
                                    </a>
                                    <span id="quantity">{{item.quantity}}</span>
                                    <button><a href="{%url 'product:pluscart' item.id %}" name='pid' class="plus-cart btn" pid="{{item.product.id}}"><i class="fas fa-plus-square fa-lg"></i>+</a></button>
                                </div>
                                <div class="d-flex justify-content-between">
                                 <a href="{%url 'product:delete' item.id %}" class="remove-cart btn btn-sm btn-secondary mr-3" name="proid"   proid="{{item.product.id}}">Remove</a>
                        
                                </div>
                            </div>
                        </div> 
                    </div>
                    
                    <hr class="text-muted">
                    {% endfor %}
                    <div class="row">
                        <h5>{{price}}</h5>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h3>Total Amount Of</h3>
                    
                    <ul class="list-group">
                        <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 pb-0">Amount <span id="amount" >Rs.{{amount}}</span></li>
                        <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0">Shipping <span>Rs.50</span></li>
                        <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 nb-3">
                            <div> 
                                <strong>Total</strong> <small>(Including GST)</small>
                            </div>
                            <span id="totalamount"><strong>Rs.{{total_amount}}</strong></span>
                        </li>
                    </ul>
            
                    <div class="d-grid"><a href="{%url 'product:order'%}" class="btn btn-primary">Place Order</a></div>
                </div>
            </div>
        </div>
        {% else %}
        <h1 class="text-center nb-5"> Cart Is Empty</h1>
       {% endif %}
    </div>
</div>
{% endblock %}
</body>

    

product/templates/order.html
<!doctype html>
<html lang="en">

<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Bootstrap demo</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style1.css' %}">
</head>
<style>
	/* Custom CSS styles */
	.product-card {
		border: 1px solid #ddd;
		box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
		padding: 10px;
		margin-bottom: 20px;
		transition: all 0.3s ease;
	}

	.product-card1 {
		border: 1px solid #ddd;

		padding: 10px;
		margin-bottom: 20px;

	}

	.product-card:hover {
		transform: translateY(-5px);
		box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);
	}

	.div1 {
		display: block;
		font-size: 16px;
		color: #7e808c;
		font-weight: 400;
		margin-bottom: 36px;
		margin-top: -30px;
	}
</style>

<body>
	{% include "navbar.html" %}
	
	<div class="container ">
		<div class="row">
			<div class="col-sm-8 product-card1">
				<div style="margin-right:25px ;">
					<h5>Choose a delivery address</h5>
				</div>
				<div>Multiple addresses in this location</div>
				<form class="row g-3">
					<div class="col-md-6">
					  <label for="inputEmail4" class="form-label">Email</label>
					  <input type="email" class="form-control" id="inputEmail4">
					</div>
					<div class="col-md-6">
					  <label for="inputPassword4" class="form-label">Password</label>
					  <input type="password" class="form-control" id="inputPassword4">
					</div>
					<div class="col-12">
					  <label for="inputAddress" class="form-label">Address</label>
					  <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
					</div>
					<div class="col-12">
					  <label for="inputAddress2" class="form-label">Address 2</label>
					  <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
					</div>
					<div class="col-md-6">
					  <label for="inputCity" class="form-label">City</label>
					  <input type="text" class="form-control" id="inputCity">
					</div>
					<div class="col-md-4">
					  <label for="inputState" class="form-label">State</label>
					  <div class="col-sm">
						<input type="text" class="form-control"  aria-label="State">
					  </div>
					  
					</div>
					<div class="col-md-2">
					  <label for="inputZip" class="form-label">Zip</label>
					  <input type="text" class="form-control" id="inputZip">
					</div>
					<div class="col-12">
					  <div class="form-check">
						<input class="form-check-input" type="checkbox" id="gridCheck">
						<label class="form-check-label" for="gridCheck">
						  Check me out
						</label>
					  </div>
					</div>
					<div class="col-12">
					  <button type="submit" class="btn btn-primary">Sign in</button>
					</div>
				  </form>

			
			</div>
		
			<div class="col-sm-4 product-card1">
				<h4>Cart Details</h4>
				<div class="card mb-3" style="max-width: 540px;">
					{% for item in data %}
		
					<div class="row g-0">
					  <div class="col-md-4" style="max-width: 100px; max-height: 150px;" >
						<img src="{{item.product.image.url}}" class="img-fluid rounded-start" alt="..." width="80px" height="80px" style="margin-top: 5px ;margin-left: 5px;">
					  </div>
					  <div class="col-md-8">
						<div class="card-body" style="margin-top: -10px; margin-left: -22px;">
						  <h6>Card title</h5>
						  <p class="mb-2 text-muted small" style=" margin-top: -5px;">This is a wider card </p>
						<div class="my-3">
							<label for="quantity" >Quantity</label>
							<button><a href="{%url 'product:minuscart' item.id %}" name="pid" class="minus-cart btn" pid="{{item.product.id}}"><i class="fas fa-minus-square fa-lg"></i>-</a></button>
							</a>
							<span id="quantity">{{item.quantity}}</span>
							<button><a href="{%url 'product:pluscart' item.id %}" name='pid' class="plus-cart btn" pid="{{item.product.id}}"><i class="fas fa-plus-square fa-lg"></i>+</a></button>
						</div>  
						  
						</div>
					  </div>
					</div>
					{% endfor %}
				  </div>
			</div>
			
		</div>
	</div>
	
</body>

product/templates/product_list.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <title>My E-commerce Site</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
</head>
<style>
    /* Custom CSS styles */
    .product-card {
        border: 1px solid #ddd;
        box-shadow: 2px 2px 5px rgba(0,0,0,0.3);
        padding: 10px;
        margin-bottom: 20px;
        transition: all 0.3s ease;
    }
    .product-card:hover {
        transform: translateY(-5px);
        box-shadow: 5px 5px 10px rgba(0,0,0,0.5);
    }
</style>

<body>

    {% include "navbar.html" %}
    {% block content %}
    <div class="container" style="margin-top: 20px; margin-left: 110px;" >
    
        <div class="row">
            {% for product in products %}
            <div class="col-md-4">
                <div class="product-card">
                    <img src="{{ product.image.url }}" class="product-image" alt="{{ product.name }}" width="328px" height="220px">

                    <div class="card-body">
                        <h5 class="card-title" style="font-size: 17px;   margin-left: 15px; font-weight: 500; margin-top: 16px;" >{{ product.name }}</h5>
                        <p class="card-text" style="color: #686b78; font-size: 13px; margin-top: 4px; margin-left: 15px;">{{ product.description }}</p>
                        <p class="card-text" style="margin-left: 15px;">Price: ${{ product.price }}</p>
                        <form action="{%url 'product:addtocart'%}" class="d-inline">
                            <input type="hidden" name="prod_id" value="{{product.id}}" />
                            <button type="submit" class="add-to-cart" style="margin-left: 15px;"> <a href="{%url 'product:addtocart'"></a> Add Cart</button>
                        </form>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>No products found.</p>
            {% endfor %}
        </div>
    
    </div>
    {% endblock %}
    </body>
</html>
                       
       
                    